### ISSUE TITLE
Works great on localhost but not on Heroku

### ISSUE THREAD

**Issue by brockklein** [amuntasim/gmap_coordinates_picker#10]
Hello Ahmed I hope you are well!

Thanks for this handy gem - saved me some time on a quick location picker form. Needed something elegant and simple and this hit the spot perfectly, especially for a n00b like me.

I'm having a problem tho. It works perfectly on **localhost**, but I just pushed to **Heroku** for testing and it fails to load.

Example here: https://www.opentest.co/share/dc6c00f04f5c11e68356998afd9fab62

Here's the form:

```
			<div class="row" style='margin-bottom: 20px;'>
				<% if defined? @latitude %>
					<%= form.gmap_coordinate_picker :latitude => 'latitude', :longitude => 'longitude', :default_coordinates => [@latitude, @longitude], :zoom_level => 10, :api_key => 'API KEY' %>
				<% else %>
					<%= form.gmap_coordinate_picker :latitude => 'latitude', :longitude => 'longitude', :zoom_level => 10, :api_key => 'API KEY' %>
				<% end %>
			</div>
```

(I know, it's bad form to pass the API key in the open - just doing this for testing before going back through and moving everything into `environments` and `secrets.yml`.)

I didn't do much with `gmap_coordinates_picker_config.rb` but here it is for reference:

```
GmapCoordinatesPicker.configure do |config|
  #config.lat_column = :latitude
  #config.lng_column = :longitude
  config.default_coordinates = [39.8282, -98.5795] #Dhaka (my home town) center point :)
  #config.map_handler = 'gMapObj' #javascript map object
  #config.zoom_level = 10
  #config.map_container_class = 'gmap_coordinate_picker_container'
  #config.map_width = '600px'
  #config.map_height = '400px'
end
```

Any suggestions on what I might be doing wrong? I'm guessing it has to do with the Google Maps API Key, but both Javascript and Places are enabled, so I'm not sure what the problem would be. I am using the key named **Browser key (auto created by Google Service)**.

The page is being served over HTTPS (if that matters).

Any help you can offer would be greatly appreciated! 

Brock

(Also, not that it matters, but below is my `Gemfile` for proof I didn't accidentally put the gem in the development group.)

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# gem 'mysql2', '0.4.2'

gem 'will_paginate', '3.0.3'

gem 'jquery-turbolinks'

gem 'mini_magick'

gem 'carrierwave'

gem 'fog'

gem 'active_model_serializers'

gem 'materialize-sass'

gem 'jquery-timepicker-rails'

gem 'time_splitter'

gem 'migration_data'

gem 'devise'

gem 'figaro'

gem 'devise_invitable'

gem 'gmap_coordinates_picker'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'rails_12factor', group: :production

ruby "2.2.3"
```

**Comment by amuntasim** [comment]
Sometimes weird things happen. Cant pinpoint the reason. But https shouldnt be an issue.
You may check the followings:

1. Need to check if any js errors
2. if you use turbolinks, you need to skip turbolinks using data-no-turbolink='true' 
3. Try with different browser

**Comment by brockklein** [comment]
Ahmed, thank you VERY much for such a quick reply.

Of course...rookie mistake on my part - I had not checked the console for JS errors. It turns out it actually is related to using HTTPS since [the gem includes](https://github.com/amuntasim/gmap_coordinates_picker/search?utf8=%E2%9C%93&q=googleapis) `http://maps.googleapis.com/maps/api/...`.

<img width="1266" alt="screen shot 2016-07-21 at 1 46 35 pm" src="https://cloud.githubusercontent.com/assets/2125662/17032921/9ac75a72-4f49-11e6-9901-4c8eca5938a1.png">

I had no idea how to intercept and replace that include tag with the `https` version so I forked the gem so I can add the `s` and source it from my forked version. =) 

`gem 'gmap_coordinates_picker', :git => 'git://github.com/brockklein/gmap_coordinates_picker'`

To be sure, I also disabled turbolinks with the method described here: http://stackoverflow.com/a/27482171/1594335

That seemed to do the trick!

When I have a moment I'll edit the files and your instructions with some suggested edits so folks can include the JS in their own Asset Pipeline instead of in the partial.

**Comment by amuntasim** [comment]
I will push an update by tomorrow replacing http with https

**Comment by brockklein** [comment]
Awesome! Sounds good.

**Comment by amuntasim** [comment]
Sorry for the huge late!
If the problem still persists, please update the gem, in 0.0.8 it got resolved.

Thanks for posting :)
