### ISSUE TITLE
undefined method `render_gmap_coordinate_picker'

### ISSUE THREAD

**Issue by BrianHuang** [amuntasim/gmap_coordinates_picker#6]
Hi, I do exactly what you demonstrated in README,
I add this line
`<%= render_gmap_coordinate_picker :static => 'true', :zoom_level => 10 , :default_coordinates => [24,120]  %>` in my index.html.erb

then it raised this error
undefined method `render_gmap_coordinate_picker'

could you help me? thanks

**Comment by amuntasim** [comment]
Did you add this gem in your gemfile and then restart your app?

**Comment by BrianHuang** [comment]
Oh, I did add this gem in my gemfile but I forget to restart, sorry for the stupid mistake. Thanks for your help.
