### ISSUE TITLE
form.gmap_coordinate_picker does't work

### ISSUE THREAD

**Issue by omarwaleed** [amuntasim/gmap_coordinates_picker#7]
whenever i call form.gmap_coordinate_picker in my form it gives the following error:
NoMethodError in Controller#Action
undefined method `hidden_field_tag' for #<ActionView::Helpers::FormBuilder:0xc01ac10>

i try calling render_gmap_coordinate_picker instead which works fine but every time i close the tab and open it again i have to refresh the view (literally pressing refresh) for the map to display or else the map takes place in the view but doesn't show.

any help?

**Comment by amuntasim** [comment]
Seems  its working, what is your Rails version btw?
Here is the demo app source code.

https://github.com/amuntasim/gmap-coordicate-picker-demo

It has some issue with turbolink and ajax rendering, you need to fix the view side if you really need that.

**Comment by omarwaleed** [comment]
my rails version is 4.2.0 and ruby version 2.1.5
i tried removing all the options like in the example you linked but still no luck :/

**Comment by amuntasim** [comment]
Did you try running the demo app?

**Comment by omarwaleed** [comment]
just tried it and it works perfectly

**Comment by omarwaleed** [comment]
i can copy the full error trace if it can help

**Comment by omarwaleed** [comment]
found a solution for render_gmap_coordinate_picker not showing until i manually refresh the page.
the problem appears to have been caused by turbolinks. the solution is quite easy, just add 
'data-no-turbolink' => true
to  your link_to method and the map will work perfectly. the form helper still gives the same error but at least that's one way to do it :D 
closing issue because that will do the job. thanks amuntasim :D

**Comment by omarwaleed** [comment]
Update: disabling turbolinks doesn't always work
