### ISSUE TITLE
Custom marker

### ISSUE THREAD

**Issue by AlyBadawy** [amuntasim/gmap_coordinates_picker#9]
Hello, thanks for this gem. Is there anyway I can use a custom marker with this?

**Comment by amuntasim** [comment]
If you notice the first couple of lines of this partial: 
https://github.com/amuntasim/gmap_coordinates_picker/blob/master/app/views/gmap_coordinate_picker/_gmap_coordinate_picker.html.erb
You have two javascript map handler and those can be customized .  default value of map handler is 'gMapObj'

So you can extend it to any levels using these map handlers and gmap apis.
